// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: MsgInfo.proto

package com.lpf.im.group2.model;

public final class MsgInfoProto {
  private MsgInfoProto() {}
  public static void registerAllExtensions(
          com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
          com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
            (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface MsgInfoOrBuilder extends
          // @@protoc_insertion_point(interface_extends:com.lpf.im.group2.model.MsgInfo)
          com.google.protobuf.MessageOrBuilder {

    /**
     * <pre>
     *接口版本号
     * </pre>
     *
     * <code>string version = 1;</code>
     */
    java.lang.String getVersion();
    /**
     * <pre>
     *接口版本号
     * </pre>
     *
     * <code>string version = 1;</code>
     */
    com.google.protobuf.ByteString
    getVersionBytes();

    /**
     * <pre>
     *请求接口命令字  1绑定  2心跳  3上线  4下线 5消息
     * </pre>
     *
     * <code>.com.lpf.im.group2.model.MsgInfo.CMDEnum cmd = 2;</code>
     */
    int getCmdValue();
    /**
     * <pre>
     *请求接口命令字  1绑定  2心跳  3上线  4下线 5消息
     * </pre>
     *
     * <code>.com.lpf.im.group2.model.MsgInfo.CMDEnum cmd = 2;</code>
     */
    com.lpf.im.group2.model.MsgInfoProto.MsgInfo.CMDEnum getCmd();

    /**
     * <pre>
     *发送人
     * </pre>
     *
     * <code>string senderId = 3;</code>
     */
    java.lang.String getSenderId();
    /**
     * <pre>
     *发送人
     * </pre>
     *
     * <code>string senderId = 3;</code>
     */
    com.google.protobuf.ByteString
    getSenderIdBytes();

    /**
     * <pre>
     *接收人
     * </pre>
     *
     * <code>string recvId = 4;</code>
     */
    java.lang.String getRecvId();
    /**
     * <pre>
     *接收人
     * </pre>
     *
     * <code>string recvId = 4;</code>
     */
    com.google.protobuf.ByteString
    getRecvIdBytes();

    /**
     * <pre>
     *请求1，应答2，通知3，响应4  format
     * </pre>
     *
     * <code>uint32 msgtype = 5;</code>
     */
    int getMsgtype();

    /**
     * <pre>
     *请求数据
     * </pre>
     *
     * <code>bytes content = 6;</code>
     */
    com.google.protobuf.ByteString getContent();
  }
  /**
   * Protobuf type {@code com.lpf.im.group2.model.MsgInfo}
   */
  public  static final class MsgInfo extends
          com.google.protobuf.GeneratedMessageV3 implements
          // @@protoc_insertion_point(message_implements:com.lpf.im.group2.model.MsgInfo)
          MsgInfoOrBuilder {
    private static final long serialVersionUID = 0L;
    // Use MsgInfo.newBuilder() to construct.
    private MsgInfo(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private MsgInfo() {
      version_ = "";
      cmd_ = 0;
      senderId_ = "";
      recvId_ = "";
      content_ = com.google.protobuf.ByteString.EMPTY;
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private MsgInfo(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
              com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              java.lang.String s = input.readStringRequireUtf8();

              version_ = s;
              break;
            }
            case 16: {
              int rawValue = input.readEnum();

              cmd_ = rawValue;
              break;
            }
            case 26: {
              java.lang.String s = input.readStringRequireUtf8();

              senderId_ = s;
              break;
            }
            case 34: {
              java.lang.String s = input.readStringRequireUtf8();

              recvId_ = s;
              break;
            }
            case 40: {

              msgtype_ = input.readUInt32();
              break;
            }
            case 50: {

              content_ = input.readBytes();
              break;
            }
            default: {
              if (!parseUnknownField(
                      input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
                e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
    getDescriptor() {
      return com.lpf.im.group2.model.MsgInfoProto.internal_static_com_lpf_im_group2_model_MsgInfo_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
    internalGetFieldAccessorTable() {
      return com.lpf.im.group2.model.MsgInfoProto.internal_static_com_lpf_im_group2_model_MsgInfo_fieldAccessorTable
              .ensureFieldAccessorsInitialized(
                      com.lpf.im.group2.model.MsgInfoProto.MsgInfo.class, com.lpf.im.group2.model.MsgInfoProto.MsgInfo.Builder.class);
    }

    /**
     * Protobuf enum {@code com.lpf.im.group2.model.MsgInfo.CMDEnum}
     */
    public enum CMDEnum
            implements com.google.protobuf.ProtocolMessageEnum {
      /**
       * <code>DEFAULT = 0;</code>
       */
      DEFAULT(0),
      /**
       * <code>ONLINE = 1;</code>
       */
      ONLINE(1),
      /**
       * <code>OFFLINE = 2;</code>
       */
      OFFLINE(2),
      /**
       * <code>MESSAGE = 3;</code>
       */
      MESSAGE(3),
      /**
       * <code>BROADCAST = 4;</code>
       */
      BROADCAST(4),
      /**
       * <code>GET_ALL_ONLINE_USERS = 5;</code>
       */
      GET_ALL_ONLINE_USERS(5),
      UNRECOGNIZED(-1),
      ;

      /**
       * <code>DEFAULT = 0;</code>
       */
      public static final int DEFAULT_VALUE = 0;
      /**
       * <code>ONLINE = 1;</code>
       */
      public static final int ONLINE_VALUE = 1;
      /**
       * <code>OFFLINE = 2;</code>
       */
      public static final int OFFLINE_VALUE = 2;
      /**
       * <code>MESSAGE = 3;</code>
       */
      public static final int MESSAGE_VALUE = 3;
      /**
       * <code>BROADCAST = 4;</code>
       */
      public static final int BROADCAST_VALUE = 4;
      /**
       * <code>GET_ALL_ONLINE_USERS = 5;</code>
       */
      public static final int GET_ALL_ONLINE_USERS_VALUE = 5;


      public final int getNumber() {
        if (this == UNRECOGNIZED) {
          throw new java.lang.IllegalArgumentException(
                  "Can't get the number of an unknown enum value.");
        }
        return value;
      }

      /**
       * @deprecated Use {@link #forNumber(int)} instead.
       */
      @java.lang.Deprecated
      public static CMDEnum valueOf(int value) {
        return forNumber(value);
      }

      public static CMDEnum forNumber(int value) {
        switch (value) {
          case 0: return DEFAULT;
          case 1: return ONLINE;
          case 2: return OFFLINE;
          case 3: return MESSAGE;
          case 4: return BROADCAST;
          case 5: return GET_ALL_ONLINE_USERS;
          default: return null;
        }
      }

      public static com.google.protobuf.Internal.EnumLiteMap<CMDEnum>
      internalGetValueMap() {
        return internalValueMap;
      }
      private static final com.google.protobuf.Internal.EnumLiteMap<
              CMDEnum> internalValueMap =
              new com.google.protobuf.Internal.EnumLiteMap<CMDEnum>() {
                public CMDEnum findValueByNumber(int number) {
                  return CMDEnum.forNumber(number);
                }
              };

      public final com.google.protobuf.Descriptors.EnumValueDescriptor
      getValueDescriptor() {
        return getDescriptor().getValues().get(ordinal());
      }
      public final com.google.protobuf.Descriptors.EnumDescriptor
      getDescriptorForType() {
        return getDescriptor();
      }
      public static final com.google.protobuf.Descriptors.EnumDescriptor
      getDescriptor() {
        return com.lpf.im.group2.model.MsgInfoProto.MsgInfo.getDescriptor().getEnumTypes().get(0);
      }

      private static final CMDEnum[] VALUES = values();

      public static CMDEnum valueOf(
              com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
        if (desc.getType() != getDescriptor()) {
          throw new java.lang.IllegalArgumentException(
                  "EnumValueDescriptor is not for this type.");
        }
        if (desc.getIndex() == -1) {
          return UNRECOGNIZED;
        }
        return VALUES[desc.getIndex()];
      }

      private final int value;

      private CMDEnum(int value) {
        this.value = value;
      }

      // @@protoc_insertion_point(enum_scope:com.lpf.im.group2.model.MsgInfo.CMDEnum)
    }

    public static final int VERSION_FIELD_NUMBER = 1;
    private volatile java.lang.Object version_;
    /**
     * <pre>
     *接口版本号
     * </pre>
     *
     * <code>string version = 1;</code>
     */
    public java.lang.String getVersion() {
      java.lang.Object ref = version_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs =
                (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        version_ = s;
        return s;
      }
    }
    /**
     * <pre>
     *接口版本号
     * </pre>
     *
     * <code>string version = 1;</code>
     */
    public com.google.protobuf.ByteString
    getVersionBytes() {
      java.lang.Object ref = version_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b =
                com.google.protobuf.ByteString.copyFromUtf8(
                        (java.lang.String) ref);
        version_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int CMD_FIELD_NUMBER = 2;
    private int cmd_;
    /**
     * <pre>
     *请求接口命令字  1绑定  2心跳  3上线  4下线 5消息
     * </pre>
     *
     * <code>.com.lpf.im.group2.model.MsgInfo.CMDEnum cmd = 2;</code>
     */
    public int getCmdValue() {
      return cmd_;
    }
    /**
     * <pre>
     *请求接口命令字  1绑定  2心跳  3上线  4下线 5消息
     * </pre>
     *
     * <code>.com.lpf.im.group2.model.MsgInfo.CMDEnum cmd = 2;</code>
     */
    public com.lpf.im.group2.model.MsgInfoProto.MsgInfo.CMDEnum getCmd() {
      @SuppressWarnings("deprecation")
      com.lpf.im.group2.model.MsgInfoProto.MsgInfo.CMDEnum result = com.lpf.im.group2.model.MsgInfoProto.MsgInfo.CMDEnum.valueOf(cmd_);
      return result == null ? com.lpf.im.group2.model.MsgInfoProto.MsgInfo.CMDEnum.UNRECOGNIZED : result;
    }

    public static final int SENDERID_FIELD_NUMBER = 3;
    private volatile java.lang.Object senderId_;
    /**
     * <pre>
     *发送人
     * </pre>
     *
     * <code>string senderId = 3;</code>
     */
    public java.lang.String getSenderId() {
      java.lang.Object ref = senderId_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs =
                (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        senderId_ = s;
        return s;
      }
    }
    /**
     * <pre>
     *发送人
     * </pre>
     *
     * <code>string senderId = 3;</code>
     */
    public com.google.protobuf.ByteString
    getSenderIdBytes() {
      java.lang.Object ref = senderId_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b =
                com.google.protobuf.ByteString.copyFromUtf8(
                        (java.lang.String) ref);
        senderId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int RECVID_FIELD_NUMBER = 4;
    private volatile java.lang.Object recvId_;
    /**
     * <pre>
     *接收人
     * </pre>
     *
     * <code>string recvId = 4;</code>
     */
    public java.lang.String getRecvId() {
      java.lang.Object ref = recvId_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs =
                (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        recvId_ = s;
        return s;
      }
    }
    /**
     * <pre>
     *接收人
     * </pre>
     *
     * <code>string recvId = 4;</code>
     */
    public com.google.protobuf.ByteString
    getRecvIdBytes() {
      java.lang.Object ref = recvId_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b =
                com.google.protobuf.ByteString.copyFromUtf8(
                        (java.lang.String) ref);
        recvId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int MSGTYPE_FIELD_NUMBER = 5;
    private int msgtype_;
    /**
     * <pre>
     *请求1，应答2，通知3，响应4  format
     * </pre>
     *
     * <code>uint32 msgtype = 5;</code>
     */
    public int getMsgtype() {
      return msgtype_;
    }

    public static final int CONTENT_FIELD_NUMBER = 6;
    private com.google.protobuf.ByteString content_;
    /**
     * <pre>
     *请求数据
     * </pre>
     *
     * <code>bytes content = 6;</code>
     */
    public com.google.protobuf.ByteString getContent() {
      return content_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
            throws java.io.IOException {
      if (!getVersionBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, version_);
      }
      if (cmd_ != com.lpf.im.group2.model.MsgInfoProto.MsgInfo.CMDEnum.DEFAULT.getNumber()) {
        output.writeEnum(2, cmd_);
      }
      if (!getSenderIdBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 3, senderId_);
      }
      if (!getRecvIdBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 4, recvId_);
      }
      if (msgtype_ != 0) {
        output.writeUInt32(5, msgtype_);
      }
      if (!content_.isEmpty()) {
        output.writeBytes(6, content_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!getVersionBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, version_);
      }
      if (cmd_ != com.lpf.im.group2.model.MsgInfoProto.MsgInfo.CMDEnum.DEFAULT.getNumber()) {
        size += com.google.protobuf.CodedOutputStream
                .computeEnumSize(2, cmd_);
      }
      if (!getSenderIdBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, senderId_);
      }
      if (!getRecvIdBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(4, recvId_);
      }
      if (msgtype_ != 0) {
        size += com.google.protobuf.CodedOutputStream
                .computeUInt32Size(5, msgtype_);
      }
      if (!content_.isEmpty()) {
        size += com.google.protobuf.CodedOutputStream
                .computeBytesSize(6, content_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
        return true;
      }
      if (!(obj instanceof com.lpf.im.group2.model.MsgInfoProto.MsgInfo)) {
        return super.equals(obj);
      }
      com.lpf.im.group2.model.MsgInfoProto.MsgInfo other = (com.lpf.im.group2.model.MsgInfoProto.MsgInfo) obj;

      if (!getVersion()
              .equals(other.getVersion())) return false;
      if (cmd_ != other.cmd_) return false;
      if (!getSenderId()
              .equals(other.getSenderId())) return false;
      if (!getRecvId()
              .equals(other.getRecvId())) return false;
      if (getMsgtype()
              != other.getMsgtype()) return false;
      if (!getContent()
              .equals(other.getContent())) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + VERSION_FIELD_NUMBER;
      hash = (53 * hash) + getVersion().hashCode();
      hash = (37 * hash) + CMD_FIELD_NUMBER;
      hash = (53 * hash) + cmd_;
      hash = (37 * hash) + SENDERID_FIELD_NUMBER;
      hash = (53 * hash) + getSenderId().hashCode();
      hash = (37 * hash) + RECVID_FIELD_NUMBER;
      hash = (53 * hash) + getRecvId().hashCode();
      hash = (37 * hash) + MSGTYPE_FIELD_NUMBER;
      hash = (53 * hash) + getMsgtype();
      hash = (37 * hash) + CONTENT_FIELD_NUMBER;
      hash = (53 * hash) + getContent().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.lpf.im.group2.model.MsgInfoProto.MsgInfo parseFrom(
            java.nio.ByteBuffer data)
            throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.lpf.im.group2.model.MsgInfoProto.MsgInfo parseFrom(
            java.nio.ByteBuffer data,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.lpf.im.group2.model.MsgInfoProto.MsgInfo parseFrom(
            com.google.protobuf.ByteString data)
            throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.lpf.im.group2.model.MsgInfoProto.MsgInfo parseFrom(
            com.google.protobuf.ByteString data,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.lpf.im.group2.model.MsgInfoProto.MsgInfo parseFrom(byte[] data)
            throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.lpf.im.group2.model.MsgInfoProto.MsgInfo parseFrom(
            byte[] data,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.lpf.im.group2.model.MsgInfoProto.MsgInfo parseFrom(java.io.InputStream input)
            throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
              .parseWithIOException(PARSER, input);
    }
    public static com.lpf.im.group2.model.MsgInfoProto.MsgInfo parseFrom(
            java.io.InputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
              .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.lpf.im.group2.model.MsgInfoProto.MsgInfo parseDelimitedFrom(java.io.InputStream input)
            throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
              .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.lpf.im.group2.model.MsgInfoProto.MsgInfo parseDelimitedFrom(
            java.io.InputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
              .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.lpf.im.group2.model.MsgInfoProto.MsgInfo parseFrom(
            com.google.protobuf.CodedInputStream input)
            throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
              .parseWithIOException(PARSER, input);
    }
    public static com.lpf.im.group2.model.MsgInfoProto.MsgInfo parseFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
              .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.lpf.im.group2.model.MsgInfoProto.MsgInfo prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
              ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
            com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code com.lpf.im.group2.model.MsgInfo}
     */
    public static final class Builder extends
            com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
            // @@protoc_insertion_point(builder_implements:com.lpf.im.group2.model.MsgInfo)
            com.lpf.im.group2.model.MsgInfoProto.MsgInfoOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
        return com.lpf.im.group2.model.MsgInfoProto.internal_static_com_lpf_im_group2_model_MsgInfo_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
        return com.lpf.im.group2.model.MsgInfoProto.internal_static_com_lpf_im_group2_model_MsgInfo_fieldAccessorTable
                .ensureFieldAccessorsInitialized(
                        com.lpf.im.group2.model.MsgInfoProto.MsgInfo.class, com.lpf.im.group2.model.MsgInfoProto.MsgInfo.Builder.class);
      }

      // Construct using com.lpf.im.group2.model.MsgInfoProto.MsgInfo.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
              com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        version_ = "";

        cmd_ = 0;

        senderId_ = "";

        recvId_ = "";

        msgtype_ = 0;

        content_ = com.google.protobuf.ByteString.EMPTY;

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
      getDescriptorForType() {
        return com.lpf.im.group2.model.MsgInfoProto.internal_static_com_lpf_im_group2_model_MsgInfo_descriptor;
      }

      @java.lang.Override
      public com.lpf.im.group2.model.MsgInfoProto.MsgInfo getDefaultInstanceForType() {
        return com.lpf.im.group2.model.MsgInfoProto.MsgInfo.getDefaultInstance();
      }

      @java.lang.Override
      public com.lpf.im.group2.model.MsgInfoProto.MsgInfo build() {
        com.lpf.im.group2.model.MsgInfoProto.MsgInfo result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.lpf.im.group2.model.MsgInfoProto.MsgInfo buildPartial() {
        com.lpf.im.group2.model.MsgInfoProto.MsgInfo result = new com.lpf.im.group2.model.MsgInfoProto.MsgInfo(this);
        result.version_ = version_;
        result.cmd_ = cmd_;
        result.senderId_ = senderId_;
        result.recvId_ = recvId_;
        result.msgtype_ = msgtype_;
        result.content_ = content_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
              com.google.protobuf.Descriptors.FieldDescriptor field,
              java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
              com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
              com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
              com.google.protobuf.Descriptors.FieldDescriptor field,
              int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
              com.google.protobuf.Descriptors.FieldDescriptor field,
              java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.lpf.im.group2.model.MsgInfoProto.MsgInfo) {
          return mergeFrom((com.lpf.im.group2.model.MsgInfoProto.MsgInfo)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.lpf.im.group2.model.MsgInfoProto.MsgInfo other) {
        if (other == com.lpf.im.group2.model.MsgInfoProto.MsgInfo.getDefaultInstance()) return this;
        if (!other.getVersion().isEmpty()) {
          version_ = other.version_;
          onChanged();
        }
        if (other.cmd_ != 0) {
          setCmdValue(other.getCmdValue());
        }
        if (!other.getSenderId().isEmpty()) {
          senderId_ = other.senderId_;
          onChanged();
        }
        if (!other.getRecvId().isEmpty()) {
          recvId_ = other.recvId_;
          onChanged();
        }
        if (other.getMsgtype() != 0) {
          setMsgtype(other.getMsgtype());
        }
        if (other.getContent() != com.google.protobuf.ByteString.EMPTY) {
          setContent(other.getContent());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
              com.google.protobuf.CodedInputStream input,
              com.google.protobuf.ExtensionRegistryLite extensionRegistry)
              throws java.io.IOException {
        com.lpf.im.group2.model.MsgInfoProto.MsgInfo parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.lpf.im.group2.model.MsgInfoProto.MsgInfo) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private java.lang.Object version_ = "";
      /**
       * <pre>
       *接口版本号
       * </pre>
       *
       * <code>string version = 1;</code>
       */
      public java.lang.String getVersion() {
        java.lang.Object ref = version_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
                  (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          version_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <pre>
       *接口版本号
       * </pre>
       *
       * <code>string version = 1;</code>
       */
      public com.google.protobuf.ByteString
      getVersionBytes() {
        java.lang.Object ref = version_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b =
                  com.google.protobuf.ByteString.copyFromUtf8(
                          (java.lang.String) ref);
          version_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       *接口版本号
       * </pre>
       *
       * <code>string version = 1;</code>
       */
      public Builder setVersion(
              java.lang.String value) {
        if (value == null) {
          throw new NullPointerException();
        }

        version_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *接口版本号
       * </pre>
       *
       * <code>string version = 1;</code>
       */
      public Builder clearVersion() {

        version_ = getDefaultInstance().getVersion();
        onChanged();
        return this;
      }
      /**
       * <pre>
       *接口版本号
       * </pre>
       *
       * <code>string version = 1;</code>
       */
      public Builder setVersionBytes(
              com.google.protobuf.ByteString value) {
        if (value == null) {
          throw new NullPointerException();
        }
        checkByteStringIsUtf8(value);

        version_ = value;
        onChanged();
        return this;
      }

      private int cmd_ = 0;
      /**
       * <pre>
       *请求接口命令字  1绑定  2心跳  3上线  4下线 5消息
       * </pre>
       *
       * <code>.com.lpf.im.group2.model.MsgInfo.CMDEnum cmd = 2;</code>
       */
      public int getCmdValue() {
        return cmd_;
      }
      /**
       * <pre>
       *请求接口命令字  1绑定  2心跳  3上线  4下线 5消息
       * </pre>
       *
       * <code>.com.lpf.im.group2.model.MsgInfo.CMDEnum cmd = 2;</code>
       */
      public Builder setCmdValue(int value) {
        cmd_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *请求接口命令字  1绑定  2心跳  3上线  4下线 5消息
       * </pre>
       *
       * <code>.com.lpf.im.group2.model.MsgInfo.CMDEnum cmd = 2;</code>
       */
      public com.lpf.im.group2.model.MsgInfoProto.MsgInfo.CMDEnum getCmd() {
        @SuppressWarnings("deprecation")
        com.lpf.im.group2.model.MsgInfoProto.MsgInfo.CMDEnum result = com.lpf.im.group2.model.MsgInfoProto.MsgInfo.CMDEnum.valueOf(cmd_);
        return result == null ? com.lpf.im.group2.model.MsgInfoProto.MsgInfo.CMDEnum.UNRECOGNIZED : result;
      }
      /**
       * <pre>
       *请求接口命令字  1绑定  2心跳  3上线  4下线 5消息
       * </pre>
       *
       * <code>.com.lpf.im.group2.model.MsgInfo.CMDEnum cmd = 2;</code>
       */
      public Builder setCmd(com.lpf.im.group2.model.MsgInfoProto.MsgInfo.CMDEnum value) {
        if (value == null) {
          throw new NullPointerException();
        }

        cmd_ = value.getNumber();
        onChanged();
        return this;
      }
      /**
       * <pre>
       *请求接口命令字  1绑定  2心跳  3上线  4下线 5消息
       * </pre>
       *
       * <code>.com.lpf.im.group2.model.MsgInfo.CMDEnum cmd = 2;</code>
       */
      public Builder clearCmd() {

        cmd_ = 0;
        onChanged();
        return this;
      }

      private java.lang.Object senderId_ = "";
      /**
       * <pre>
       *发送人
       * </pre>
       *
       * <code>string senderId = 3;</code>
       */
      public java.lang.String getSenderId() {
        java.lang.Object ref = senderId_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
                  (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          senderId_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <pre>
       *发送人
       * </pre>
       *
       * <code>string senderId = 3;</code>
       */
      public com.google.protobuf.ByteString
      getSenderIdBytes() {
        java.lang.Object ref = senderId_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b =
                  com.google.protobuf.ByteString.copyFromUtf8(
                          (java.lang.String) ref);
          senderId_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       *发送人
       * </pre>
       *
       * <code>string senderId = 3;</code>
       */
      public Builder setSenderId(
              java.lang.String value) {
        if (value == null) {
          throw new NullPointerException();
        }

        senderId_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *发送人
       * </pre>
       *
       * <code>string senderId = 3;</code>
       */
      public Builder clearSenderId() {

        senderId_ = getDefaultInstance().getSenderId();
        onChanged();
        return this;
      }
      /**
       * <pre>
       *发送人
       * </pre>
       *
       * <code>string senderId = 3;</code>
       */
      public Builder setSenderIdBytes(
              com.google.protobuf.ByteString value) {
        if (value == null) {
          throw new NullPointerException();
        }
        checkByteStringIsUtf8(value);

        senderId_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object recvId_ = "";
      /**
       * <pre>
       *接收人
       * </pre>
       *
       * <code>string recvId = 4;</code>
       */
      public java.lang.String getRecvId() {
        java.lang.Object ref = recvId_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
                  (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          recvId_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <pre>
       *接收人
       * </pre>
       *
       * <code>string recvId = 4;</code>
       */
      public com.google.protobuf.ByteString
      getRecvIdBytes() {
        java.lang.Object ref = recvId_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b =
                  com.google.protobuf.ByteString.copyFromUtf8(
                          (java.lang.String) ref);
          recvId_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       *接收人
       * </pre>
       *
       * <code>string recvId = 4;</code>
       */
      public Builder setRecvId(
              java.lang.String value) {
        if (value == null) {
          throw new NullPointerException();
        }

        recvId_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *接收人
       * </pre>
       *
       * <code>string recvId = 4;</code>
       */
      public Builder clearRecvId() {

        recvId_ = getDefaultInstance().getRecvId();
        onChanged();
        return this;
      }
      /**
       * <pre>
       *接收人
       * </pre>
       *
       * <code>string recvId = 4;</code>
       */
      public Builder setRecvIdBytes(
              com.google.protobuf.ByteString value) {
        if (value == null) {
          throw new NullPointerException();
        }
        checkByteStringIsUtf8(value);

        recvId_ = value;
        onChanged();
        return this;
      }

      private int msgtype_ ;
      /**
       * <pre>
       *请求1，应答2，通知3，响应4  format
       * </pre>
       *
       * <code>uint32 msgtype = 5;</code>
       */
      public int getMsgtype() {
        return msgtype_;
      }
      /**
       * <pre>
       *请求1，应答2，通知3，响应4  format
       * </pre>
       *
       * <code>uint32 msgtype = 5;</code>
       */
      public Builder setMsgtype(int value) {

        msgtype_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *请求1，应答2，通知3，响应4  format
       * </pre>
       *
       * <code>uint32 msgtype = 5;</code>
       */
      public Builder clearMsgtype() {

        msgtype_ = 0;
        onChanged();
        return this;
      }

      private com.google.protobuf.ByteString content_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <pre>
       *请求数据
       * </pre>
       *
       * <code>bytes content = 6;</code>
       */
      public com.google.protobuf.ByteString getContent() {
        return content_;
      }
      /**
       * <pre>
       *请求数据
       * </pre>
       *
       * <code>bytes content = 6;</code>
       */
      public Builder setContent(com.google.protobuf.ByteString value) {
        if (value == null) {
          throw new NullPointerException();
        }

        content_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *请求数据
       * </pre>
       *
       * <code>bytes content = 6;</code>
       */
      public Builder clearContent() {

        content_ = getDefaultInstance().getContent();
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
              final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
              final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:com.lpf.im.group2.model.MsgInfo)
    }

    // @@protoc_insertion_point(class_scope:com.lpf.im.group2.model.MsgInfo)
    private static final com.lpf.im.group2.model.MsgInfoProto.MsgInfo DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.lpf.im.group2.model.MsgInfoProto.MsgInfo();
    }

    public static com.lpf.im.group2.model.MsgInfoProto.MsgInfo getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<MsgInfo>
            PARSER = new com.google.protobuf.AbstractParser<MsgInfo>() {
      @java.lang.Override
      public MsgInfo parsePartialFrom(
              com.google.protobuf.CodedInputStream input,
              com.google.protobuf.ExtensionRegistryLite extensionRegistry)
              throws com.google.protobuf.InvalidProtocolBufferException {
        return new MsgInfo(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<MsgInfo> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<MsgInfo> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.lpf.im.group2.model.MsgInfoProto.MsgInfo getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
          internal_static_com_lpf_im_group2_model_MsgInfo_descriptor;
  private static final
  com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internal_static_com_lpf_im_group2_model_MsgInfo_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
  getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
          descriptor;
  static {
    java.lang.String[] descriptorData = {
            "\n\rMsgInfo.proto\022\027com.lpf.im.group2.model" +
                    "\"\374\001\n\007MsgInfo\022\017\n\007version\030\001 \001(\t\0225\n\003cmd\030\002 \001" +
                    "(\0162(.com.lpf.im.group2.model.MsgInfo.CMD" +
                    "Enum\022\020\n\010senderId\030\003 \001(\t\022\016\n\006recvId\030\004 \001(\t\022\017" +
                    "\n\007msgtype\030\005 \001(\r\022\017\n\007content\030\006 \001(\014\"e\n\007CMDE" +
                    "num\022\013\n\007DEFAULT\020\000\022\n\n\006ONLINE\020\001\022\013\n\007OFFLINE\020" +
                    "\002\022\013\n\007MESSAGE\020\003\022\r\n\tBROADCAST\020\004\022\030\n\024GET_ALL" +
                    "_ONLINE_USERS\020\005B\016B\014MsgInfoProtob\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
            new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
              public com.google.protobuf.ExtensionRegistry assignDescriptors(
                      com.google.protobuf.Descriptors.FileDescriptor root) {
                descriptor = root;
                return null;
              }
            };
    com.google.protobuf.Descriptors.FileDescriptor
            .internalBuildGeneratedFileFrom(descriptorData,
                    new com.google.protobuf.Descriptors.FileDescriptor[] {
                    }, assigner);
    internal_static_com_lpf_im_group2_model_MsgInfo_descriptor =
            getDescriptor().getMessageTypes().get(0);
    internal_static_com_lpf_im_group2_model_MsgInfo_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
            internal_static_com_lpf_im_group2_model_MsgInfo_descriptor,
            new java.lang.String[] { "Version", "Cmd", "SenderId", "RecvId", "Msgtype", "Content", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
